from datetime import datetime
from typing import List, Dict, Any

class ICSExporter:
    """Generates standard iCalendar (.ics) string for study sessions."""

    @classmethod
    def generate_ics(cls, sessions: List[Dict[str, Any]]) -> str:
        lines = [
            "BEGIN:VCALENDAR",
            "VERSION:2.0",
            "PRODID:-//AI Study Planner//EN",
            "CALSCALE:GREGORIAN",
            "METHOD:PUBLISH"
        ]

        for s in sessions:
            try:
                date_str = s.get("date", "").replace("-", "")
                start_time = s.get("start", "18:00").replace(":", "") + "00"
                end_time = s.get("end", "19:00").replace(":", "") + "00"
                
                dtstart = f"{date_str}T{start_time}"
                dtend = f"{date_str}T{end_time}"
                
                summary = f"[{s.get('kind', 'study').upper()}] {s.get('subject_name', '')}: {s.get('topic_name', '')}"
                description = f"Study Session generated by AI Study Planner.\\nTopic: {s.get('topic_name')}\\nStatus: {s.get('status')}"
                
                uid = f"session-{s.get('id', 0)}-{dtstart}@studyplanner.ai"
                
                lines.extend([
                    "BEGIN:VEVENT",
                    f"UID:{uid}",
                    f"DTSTAMP:{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}",
                    f"DTSTART:{dtstart}",
                    f"DTEND:{dtend}",
                    f"SUMMARY:{summary}",
                    f"DESCRIPTION:{description}",
                    "STATUS:CONFIRMED",
                    "END:VEVENT"
                ])
            except Exception as e:
                print(f"[ICS Error] {e}")

        lines.append("END:VCALENDAR")
        return "\r\n".join(lines)

ics_exporter = ICSExporter()
